### ISSUE TITLE
Setting up a github actions workflow fails

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [StackExchange/dnscontrol#1576]
Hi mates!

I am trying to add a github workflow to our demo dnscontrol configuration repository and this fails. I am not having an exact idea why, is this a result of a wrong configuration file maybe? I know that especially this has changed over the last releases and I am unsure if I adapted it correctly for us.

Find creds.json and dsnconfig.js here:
https://github.com/hexonet/dnscontrol-dnsconfig/tree/addworkflow

... and the github actions workflow here:
https://github.com/hexonet/dnscontrol-dnsconfig/blob/addworkflow/.github/workflows/test.yml

the result remains:
https://github.com/hexonet/dnscontrol-dnsconfig/runs/7026333785

I can ensure that the exemplary dnszone for the domain in the config file exists in the OT&E System we connect to and the credentials provided are valid. I compared this also with the HEXONET provider docs, to ensure I've not missed something.
Thanks for the help in advance!

Cheers
Kai / HEXONET

**Comment by tlimoncelli** [comment]
Interesting!  Is there a chance the credentials aren't getting set?

---

By the way... we do something like this:

```
jobs:
  preview_dns:
    name: Preview DNS - External
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: What is our path
      run: |
        echo $PATH
        pwd

    - name: Write creds.json
      [redacted magic that creates creds.json]

    - name: DNSControl Preview
      run: bin/dnscontrol-Linux preview | bin/filter-preview.sh | tee preview.txt
      id: dnscontrol_preview

    - name: Delete creds.json
      run: 'shred -u creds.json'

    - name: Attach Preview as PR comment
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.SVC_GITHUBRO_PAT }}
      with:
        path: preview.txt
```

The file `bin/filter-preview.sh` is:

```
#!/bin/bash

exec grep -v -e '^\.\.\.0 corrections$' \
   -e '^ *$' \
   -e '^0 corrections' \
   -e '\.\.\. \(skipping\)' \
   -e '^----- DNS Provider: ' \
   -e '^----- Registrar: ' \
   -e '^----- Getting nameservers from:'
```


Caveat: The pr-comments software is a bit old.  We plan on moving to using `gh` in the future. I haven't tried this but I think it will look something like:

```
    - name: Create Pull Request
      run: gh pr create --title "insert title" --body-file preview.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
