### ISSUE TITLE
Docker image - Build version 

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1687]
@tlimoncelli [commented](https://github.com/StackExchange/dnscontrol/pull/1681#discussion_r943374965)

>*You could extract it from main.go:*
>```bash
>grep -E "Version *= \"" main.go  | awk '{ print $3 }' | tr -d \"
>```

Make the Docker image build version `DOCKER_IMAGE_VERSION` aware of the [configured version](https://github.com/StackExchange/dnscontrol/blob/master/main.go#L22) in `main.go`.

```yaml
  build-docker-image:
    docker:
      - image: jdrouet/docker-with-buildx:stable

    environment:
      DOCKER_IMAGE_NAME: stackexchange/dnscontrol
      DOCKER_IMAGE_VERSION: 3.18.1
      DOCKER_IMAGE_PLATFORM: linux/amd64,linux/386
```
*https://github.com/StackExchange/dnscontrol/blob/master/.circleci/config.yml#L21*

```go
var (
	SHA       = ""
	Version   = "v3.18.1"
	BuildTime = ""
)
```
*https://github.com/StackExchange/dnscontrol/blob/master/main.go#L22*
