### ISSUE TITLE
Docker image - Multi-arch

### ISSUE THREAD

**Issue by cafferata** [StackExchange/dnscontrol#1689]
@jauderho [commented](https://github.com/StackExchange/dnscontrol/pull/1681#issuecomment-1211523288)

>*You might want to add the parameters to create multi-arch images if available/possible. Right now it looks like only amd64 is created.*

The Docker image build is multi-arch compatible `DOCKER_IMAGE_PLATFORM`. Which arches works out of the box? What else do we want to add?

```yaml
  build-docker-image:
    docker:
      - image: jdrouet/docker-with-buildx:stable

    environment:
      DOCKER_IMAGE_NAME: stackexchange/dnscontrol
      DOCKER_IMAGE_VERSION: 3.18.1
      DOCKER_IMAGE_PLATFORM: linux/amd64,linux/386
```
*https://github.com/StackExchange/dnscontrol/blob/master/.circleci/config.yml#L21*

<img width="1280" alt="docker-hub-stackexchange-dnscontrol-multi-arch-build" src="https://user-images.githubusercontent.com/1150425/184149171-ac8a111d-2162-410a-b112-1b4283a7893b.png">

*https://hub.docker.com/r/stackexchange/dnscontrol/tags*
