### ISSUE TITLE
Improvements to GitHub Release Creations

### ISSUE THREAD

**Issue by cdhunt** [StackExchange/dnscontrol#1709]
Specify more [Release](https://goreleaser.com/customization/release/) settings in the GoReleaser config.

```yaml
  draft: true
  prerelease: auto
  name_template: "Release  v{{.Version}}"
```

We should create a draft release so @tlimoncelli can customize the release notes.
