### ISSUE TITLE
The "Provider Features" table is too wide; users don't naturally see the right-most columns

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#3305]
**Describe the bug**

The "Provider Features" table is too wide; users don't naturally see the right-most columns

This page: https://docs.dnscontrol.org/getting-started/providers

**To Reproduce**
1. Go to `https://docs.dnscontrol.org/getting-started/providers`
2. You can't (without scrolling) see the right column.
3. When you do scroll, you don't see the row heads (provider names).

**Expected behavior**
Users should always see the row headers.

Some ideas:
* Replace the rtype columns (ALIAS, CAA, HTTPS, LOC, NAPTR, PTR, SOA, SRV, SSHFP, SVCB, TLSA, DS, DHCID, DNAME, DNSKEY) with a single column that lists the names of the supported records: A, MX, CNAME, LOC, PTR, TLSA.
  * The list should be a fixed-width, and word-wrap.
  * The list doesn't have to list records that all providers support: A, MX, CNAME
* Alternatively, make a 2nd table that just lists which record types are supported.

**DNS Provider**
 - n/a
 
**Additional context**
CC @cafferata

**Comment by cafferata** [comment]
Thanks for raising this issue! I agree that the current “[Provider Features](https://docs.dnscontrol.org/getting-started/providers#provider-features)” table is quite wide, and it might not offer the best user experience.

However, I’m starting to wonder if this table should even be supported going forward. I’ve always questioned what this table really tells me, especially when I’m not using the specific providers listed. Instead, I previously suggested in https://github.com/StackExchange/dnscontrol/issues/1998 that we move this information to the individual provider pages. This way, everything can be consolidated in one place for each provider, including:

* Configuration
* Metadata
* Supported features
* Usage examples
* Limitations/Known issues
* Maintainer info
* And more…

What do you think of this idea? I believe it would provide a cleaner, more useful structure.

Looking forward to hearing your thoughts!

**Comment by tlimoncelli** [comment]
Thank you for the feedback!

I see the value of putting this information on the individual provider pages, but it is also useful to have a table.  There is marketing value to being able to point people to a big list of providers, with indications of which have official support, and which are registrar-only, dns-only, or both.  It helps people know if DNSControl is right for them.  It also (hopefully) shames vendors who's support is limited.

Tom

**Comment by cafferata** [comment]
As soon as I have the time, I will work on preparing a suitable layout.

**Comment by eliheady** [comment]
Before finding this issue, I messed around with some CSS rules to make the top table row and first table column 'sticky' so they don't move while scrolling. It is like Excel's freeze rows feature.

But I don't know how or if it is possible to include custom CSS in a Gitbook site.

Here is something that 'works' in Chrome. Disclaimer: I am not a front-end dev, not tested in other browsers, etc.

```css
/* 'marketing' docs providers index features a table with
provider capabilities. The table is large in both x and y
and hard to read. These rules make the top row and leftmost
column sticky, and add scrolling for y direction with a 
static height arbitrarily set to 1000px.

https://docs.dnscontrol.org/provider/index#provider-features
*/


/* not needed? */
/*
.table_cell__X_gFM:not(:first-child) div p {
    z-index: 1000;
}

.table_row__LpfCG:first-child {
    overflow-wrap: break-word;
}
*/

/* table header */
.table_row__LpfCG:first-child {
    z-index: 1000;
    position: sticky;
    top: 0;
    border-bottom: 1px solid rgb(var(--tint-6));
    background: rgb(var(--tint-1));
}

.mx-auto.w-full.decoration-primary\/6.max-w-3xl.page-api-block\:ml-0.table_tableWrapper__zr7LC {
    height: 1000px;
    overflow-y: auto;
}

/* first column */
.table_cell__X_gFM:first-child {
    position: sticky;
    left: 0;
    z-index: 999;
    background: rgb(var(--tint-1));
    width:  clamp(175px, 4.16667% + 0px, 100%) !important;
    min-width:  clamp(170px, 4.16667% + 0px, 100%) !important;
}

.mx-auto.w-full.decoration-primary\/6.max-w-3xl.page-api-block\:ml-0.table_tableWrapper__zr7LC {
    height: 700px;
    overflow-y: auto;
}

.table_row__LpfCG:first-child div p {
    width: 5.5rem;
}
```
